version: "3.9"

services:
  mongo-exampledb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017

  code_example_1:
    build: ./grpc_server_example_1
    image: code_example_1:latest
    container_name:  code_example_1
    command: "python manage.py runserver 50051"
    volumes:
      - ./proto:/app/proto
    depends_on:
      mongo-exampledb:
        condition: service_started
    ports:
      - 50051:50051

  code_example_2:
    build: ./grpc_server_example_2
    image: code_example_2:latest
    container_name: code_example_2
    command: "python main.py runserver 50051"
    volumes:
      - ./proto:/app/proto
    depends_on:
      mongo-exampledb:
        condition: service_started
    ports:
      - 50051:50051
