version: "3.9"

services:
  # Databases, uncomment ports if you want to check data in a given database 
  mongo-accommodation:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #ports:
    #- 27017:27017
  
  mongo-auth:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #ports:
    #- 27017:27017

  mongo-availability:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #ports:
    #- 27017:27017
  
  mongo-reservation:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #ports:
    #- 27017:27017
  
  mongo-user_control:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #ports:
    #- 27017:27017
  
  # Services, expose ports when you want to test your grpc service manually
  # Running ports are not that important, but it can be easier to differentiate between services
  accommodation:
    build: ./accommodation
    image: accommodation:latest
    container_name: accommodation
    command: "python main.py runserver 50051"
    volumes:
      - ./proto:/app/proto
    depends_on:
      - mongo-accommodation
    #ports:
    #- 50051:50051
    
  auth:
    build: ./auth
    image: auth:latest
    container_name: auth
    command: "python main.py runserver 50052"
    volumes:
      - ./proto:/app/proto
    depends_on:
      - mongo-auth
    #ports:
    #- 50052:50052 
 
  availability:
    build: ./availability
    image: availability:latest
    container_name: availability
    command: "python main.py runserver 50053"
    volumes:
      - ./proto:/app/proto
    depends_on:
      - mongo-availability
    #ports:
    #- 50053:50053

  reservation:
    build: ./reservation
    image: reservation:latest
    container_name: reservation
    command: "python main.py runserver 50054"
    volumes:
      - ./proto:/app/proto
    depends_on:
      - mongo-reservation
    #ports:
    #- 50054:50054
  
  search:
    build: ./search
    image: search:latest
    container_name: search
    command: "python main.py runserver 50055"
    volumes:
      - ./proto:/app/proto
    #ports:
    #- 50055:50055

  user_control:
    build: ./user_control
    image: user_control:latest
    container_name: user_control
    command: "python main.py runserver 50056"
    volumes:
      - ./proto:/app/proto
    depends_on:
      - mongo-user_control
    #ports:
    #- 50056:50056

  notification:
    build: ./notification
    image: notification:latest
    container_name: notification
    command: "python main.py runserver 50057"
    volumes:
      - ./proto:/app/proto

  review:
    build: ./review
    image: review:latest
    container_name: review
    command: "python main.py runserver 50058"
    volumes:
      - ./proto:/app/proto

  api_gateway:
    build: ./api_gateway
    image: api_gateway:latest
    container_name: api_gateway
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./proto:/app/proto
    ports:
      - 8000:8000
  
  cdn:
    build: ./cdn
    image: cdn 
    container_name: cdn 
    command: "uvicorn main:app --host 0.0.0.0 --port 8001"
    #ports:
    #  - 8001:8001

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9094:9094
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    depends_on:
      - zookeeper
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:9092"
    depends_on:
      - "kafka"

