app:
  debug: True
  title: "Booking Services App"
  version: "1.0"
  api_prefix: "v1"
  static_prefix: "static"

static_server:
  url: "http://static_resources_server:8001/api/resources/images/"
  image_file_type: ".png"
