app:
  debug: True
  title: "Booking Services App"
  version: "1.0"
  api_prefix: "v1"
  static_prefix: "static"

reservation_server:
  ip: "reservation"
  port: "50054"

accommodation_server:
  ip: "accommodation"
  port: "50051"

auth_server:
  ip: "auth"
  port: "50052"

availability_server:
  ip: "availability"
  port: "50053"

user_server:
  ip: "user_control"
  port: "50056"

search_server:
  ip: "search"
  port: "50055"

static_server:
  url: "http://cdn:8001/api/resources/images/"
  image_file_type: ".png"

