app:
  debug: True
  title: "Booking Services App"
  version: "1.0"
  api_prefix: "v1"
  static_prefix: "static"

kafka_server:
  ip: "kafka"
  port: "9092"

accommodation_server:
  ip: "accommodation"
  port: "50051"

auth_server:
  ip: "auth"
  port: "50052"

availability_server:
  ip: "availability"
  port: "50053"

reservation_server:
  ip: "reservation"
  port: "50054"

search_server:
  ip: "search"
  port: "50055"

user_server:
  ip: "user_control"
  port: "50056"

notification_server:
  ip: "notification"
  port: "50057"

review_server:
  ip: "review"
  port: "50058"

orchestrator_server:
  ip: "orchestrator"
  port: "50059"

recomdender_server:
  ip: "accommodation_recomender"
  port: "50060"

airline_server:
  ip: "app"
  port: "8000"

static_server:
  url: "http://cdn:8001/api/resources/images/"
  image_file_type: ".png"

loki:
  url: "loki:3100"
  service: "api-gateway"
