mongodb:
  ip: "mongo-accommodation"
  port: "27017"
  username: "root"
  password: "root"
  db: "accommodation"

loki:
  url: "loki:3100"
  service: "accommodation-service"

kafka_server:
  ip: "kafka"
  port: "9092"