# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\"d\n\x0c\x45mptyMessage\x12\x1a\n\rerror_message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nerror_code\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x10\n\x0e_error_messageB\r\n\x0b_error_code\"_\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0chome_address\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\"\xbd\x01\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x11\n\tlast_name\x18\x03 \x01(\t\x12\x14\n\x0chome_address\x18\x04 \x01(\t\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12\x1a\n\rerror_message\x18\x06 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nerror_code\x18\x07 \x01(\x05H\x01\x88\x01\x01\x42\x10\n\x0e_error_messageB\r\n\x0b_error_code\"\x14\n\x06UserId\x12\n\n\x02id\x18\x01 \x01(\t2\x94\x01\n\x0bUserService\x12 \n\x08Register\x12\x05.User\x1a\r.EmptyMessage\x12!\n\x07GetById\x12\x07.UserId\x1a\r.UserResponse\x12\x1e\n\x06Update\x12\x05.User\x1a\r.EmptyMessage\x12 \n\x06\x44\x65lete\x12\x07.UserId\x1a\r.EmptyMessageb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTYMESSAGE._serialized_start=14
  _EMPTYMESSAGE._serialized_end=114
  _USER._serialized_start=116
  _USER._serialized_end=211
  _USERRESPONSE._serialized_start=214
  _USERRESPONSE._serialized_end=403
  _USERID._serialized_start=405
  _USERID._serialized_end=425
  _USERSERVICE._serialized_start=428
  _USERSERVICE._serialized_end=576
# @@protoc_insertion_point(module_scope)
