mongodb:
  ip: "mongo-availability"
  port: "27017"
  username: "root"
  password: "root"
  db: "availability"

loki:
  url: "loki:3100"
  service: "availability-service"

kafka_server:
  ip: "kafka"
  port: "9092"