neo4j:
  ip: "neo4j_recomender"
  port: "7687"
  username: "neo4j"
  password: "root"
  db: "recomender"

kafka_server:
  ip: "kafka"
  port: "9092"

loki:
  url: "loki:3100"
  service: "accommodation-recommendation-service"
