# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accommodation_recomender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x61\x63\x63ommodation_recomender.proto\"\x15\n\x07User_id\x12\n\n\x02id\x18\x01 \x01(\t\" \n\x11\x41\x63\x63ommodation_ids\x12\x0b\n\x03ids\x18\x01 \x03(\t2H\n\x17\x41\x63\x63ommodationRecomender\x12-\n\rGetRecomended\x12\x08.User_id\x1a\x12.Accommodation_idsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'accommodation_recomender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER_ID._serialized_start=34
  _USER_ID._serialized_end=55
  _ACCOMMODATION_IDS._serialized_start=57
  _ACCOMMODATION_IDS._serialized_end=89
  _ACCOMMODATIONRECOMENDER._serialized_start=91
  _ACCOMMODATIONRECOMENDER._serialized_end=163
# @@protoc_insertion_point(module_scope)
