# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: availabillity_crud.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61vailabillity_crud.proto\"\x07\n\x05\x45mpty\"\x18\n\x06Result\x12\x0e\n\x06status\x18\x01 \x01(\t\"C\n\rSearchDetails\x12\x1b\n\x08interval\x18\x01 \x01(\x0b\x32\t.Interval\x12\x15\n\rnum_of_guests\x18\x02 \x01(\t\"\x1c\n\x0e\x41vailabilityId\x12\n\n\x02id\x18\x01 \x01(\t\"7\n\x0eSpecialPricing\x12\r\n\x05title\x18\x01 \x01(\t\x12\x16\n\x0epricing_markup\x18\x02 \x01(\x01\"0\n\x08Interval\x12\x12\n\ndate_start\x18\x01 \x01(\t\x12\x10\n\x08\x64\x61te_end\x18\x02 \x01(\t\"\xdb\x01\n\x0f\x41vailabilityDto\x12\x17\n\x0f\x61vailability_id\x18\x01 \x01(\t\x12\x17\n\x0f\x61\x63\x63omodation_id\x18\x02 \x01(\t\x12\x1b\n\x08interval\x18\x03 \x01(\x0b\x32\t.Interval\x12\x14\n\x0cpricing_type\x18\x04 \x01(\t\x12\x12\n\nbase_price\x18\x05 \x01(\x01\x12(\n\x0fspecial_pricing\x18\x06 \x03(\x0b\x32\x0f.SpecialPricing\x12%\n\x12occupied_intervals\x18\x07 \x03(\x0b\x32\t.Interval\"3\n\x10\x41vailabilityDtos\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.AvailabilityDto2\x86\x02\n\x10\x41vailabilityCrud\x12#\n\x06GetAll\x12\x06.Empty\x1a\x11.AvailabilityDtos\x12\x31\n\x0cGetAllSearch\x12\x0e.SearchDetails\x1a\x11.AvailabilityDtos\x12,\n\x07GetById\x12\x0f.AvailabilityId\x1a\x10.AvailabilityDto\x12#\n\x06\x43reate\x12\x10.AvailabilityDto\x1a\x07.Result\x12\"\n\x06\x44\x65lete\x12\x0f.AvailabilityId\x1a\x07.Result\x12#\n\x06Update\x12\x10.AvailabilityDto\x1a\x07.Resultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'availabillity_crud_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=28
  _EMPTY._serialized_end=35
  _RESULT._serialized_start=37
  _RESULT._serialized_end=61
  _SEARCHDETAILS._serialized_start=63
  _SEARCHDETAILS._serialized_end=130
  _AVAILABILITYID._serialized_start=132
  _AVAILABILITYID._serialized_end=160
  _SPECIALPRICING._serialized_start=162
  _SPECIALPRICING._serialized_end=217
  _INTERVAL._serialized_start=219
  _INTERVAL._serialized_end=267
  _AVAILABILITYDTO._serialized_start=270
  _AVAILABILITYDTO._serialized_end=489
  _AVAILABILITYDTOS._serialized_start=491
  _AVAILABILITYDTOS._serialized_end=542
  _AVAILABILITYCRUD._serialized_start=545
  _AVAILABILITYCRUD._serialized_end=807
# @@protoc_insertion_point(module_scope)
