# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notification.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12notification.proto\x12\x0cnotification\"]\n\x05\x45mpty\x12\x1a\n\rerror_message\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nerror_code\x18\x02 \x01(\x05H\x01\x88\x01\x01\x42\x10\n\x0e_error_messageB\r\n\x0b_error_code\"D\n\x06Sender\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x07picture\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_picture\"\x16\n\x08Receiver\x12\n\n\x02id\x18\x01 \x01(\t\")\n\rAccommodation\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\xdd\x01\n\x0cNotification\x12\x10\n\x03key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0c\n\x04type\x18\x02 \x01(\t\x12$\n\x06sender\x18\x03 \x01(\x0b\x32\x14.notification.Sender\x12(\n\x08receiver\x18\x04 \x01(\x0b\x32\x16.notification.Receiver\x12\x32\n\raccommodation\x18\x05 \x01(\x0b\x32\x1b.notification.Accommodation\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x11\n\ttimestamp\x18\x07 \x01(\tB\x06\n\x04_key2N\n\x13NotificationService\x12\x37\n\x04Send\x12\x1a.notification.Notification\x1a\x13.notification.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notification_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=36
  _EMPTY._serialized_end=129
  _SENDER._serialized_start=131
  _SENDER._serialized_end=199
  _RECEIVER._serialized_start=201
  _RECEIVER._serialized_end=223
  _ACCOMMODATION._serialized_start=225
  _ACCOMMODATION._serialized_end=266
  _NOTIFICATION._serialized_start=269
  _NOTIFICATION._serialized_end=490
  _NOTIFICATIONSERVICE._serialized_start=492
  _NOTIFICATIONSERVICE._serialized_end=570
# @@protoc_insertion_point(module_scope)
