mongodb:
  ip: "mongo-reservation"
  port: "27017"
  username: "root"
  password: "root"
  db: "reservation"

loki:
  url: "loki:3100"
  service: "reservation-service"
kafka_server:
  ip: "kafka"
  port: "9092"
