mongodb:
  ip: "mongo-user_control"
  port: "27017"
  username: "root"
  password: "root"
  db: "user_control"

loki:
  url: "loki:3100"
  service: "user-control-service"

kafka_server:
  ip: "kafka"
  port: "9092"